export { BgType } from './enum'
export type { OldSettingsInterface } from './old'
export type { SettingsInterfaceVer2 } from './v2'
export type { SettingsInterfaceVer3 } from './v3'
export type { SettingsInterfaceVer4 } from './v4'
