export { BgType } from './enum'
export type { OldSettingsInterface } from './old'
export type { SettingsInterfaceVer2 } from './v2'
export type { SettingsInterfaceVer3 } from './v3'
export type { SettingsInterfaceVer4 } from './v4'
export type { SettingsInterfaceVer5 } from './v5'
export type { SettingsInterfaceVer6 } from './v6'
export type { SettingsInterfaceVer7 } from './v7'
export type { SettingsInterfaceVer8 } from './v8'
