name: Build And Release
permissions:
  contents: write
on:
  push:
    tags:
      - 'v*' # 匹配以 v 开头的 tag，例如 v1.0.0
  workflow_dispatch:
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install and Build
        run: |
          pnpm install
          pnpm zip
          pnpm zip -b edge
          pnpm zip -b firefox

      - name: Replace version with commit hash for non-tag builds
        if: github.event_name != 'push'
        run: |
          SHORT_HASH=$(echo "${{ github.sha }}" | cut -c1-7)
          cd .output
          for file in lemon-tab-page-*.zip; do
            if [ -f "$file" ]; then
              new_name=$(echo "$file" | sed -E 's/-[0-9.]+-/-'"$SHORT_HASH"'-/')
              mv "$file" "$new_name"
              echo "Renamed $file to $new_name"
            fi
          done

      - name: Set artifact name
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "ARTIFACT_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "ARTIFACT_NAME=dev" >> $GITHUB_ENV
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          include-hidden-files: true
          path: .output/lemon-tab-page-*.zip

      - name: Release Tag
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: .output/lemon-tab-page-*.zip
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}

      - name: Delete existing dev-release (release and tag)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v8
        with:
          script: |
            const { owner, repo } = context.repo;
            const tag = 'dev-release';
            try {
              const rel = await github.rest.repos.getReleaseByTag({ owner, repo, tag });
              await github.rest.repos.deleteRelease({ owner, repo, release_id: rel.data.id });
              core.info(`Deleted existing release for tag ${tag}`);
            } catch (e) {
              core.info(`No existing release for tag ${tag}.`);
            }
            try {
              await github.rest.git.deleteRef({ owner, repo, ref: `tags/${tag}` });
              core.info(`Deleted tag ${tag}`);
            } catch (e) {
              core.info(`No tag ref ${tag} to delete.`);
            }

      - name: Release Dev
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          files: .output/lemon-tab-page-*.zip
          name: dev-release
          tag_name: dev-release
          prerelease: true
          target_commitish: ${{ github.sha }}
          overwrite_files: true
          make_latest: false
